FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
ARG PORT

COPY package*.json ./
RUN npm ci

COPY prisma.config.ts ./
COPY prisma ./prisma
RUN npx prisma generate

COPY tsconfig*.json nest-cli.json ./
COPY src ./src

EXPOSE ${PORT}

CMD ["npm", "run", "start:dev"]
